from typing import List, Tuple
from bitarray import bitarray


def convert_binarray_to_lampel_ziv_list(data: bitarray, search_length: int = 1) -> List[Tuple[int, int, int]]:
    """
    Performs Lempel-Ziv (LZ77) compression on a binary array.

    Args:
        data (bitarray): The input binary data to be compressed.
        search_length (int): The maximum length of substrings to search for. Default is 1.

    Returns:
        List[Tuple[int, int, int]]: A list of tuples representing the compressed data.
        Each tuple typically contains (offset, length, next_symbol).
    """
    pass


def convert_lampel_ziv_list_to_binarray(lz_list: List[Tuple[int, int, int]]) -> bitarray:
    """
    Converts a list of Lempel-Ziv tuples back into a binary array format.

    Args:
        lz_list (List[Tuple[int, int, int]]): The list of LZ tuples
        (offset, length, next_symbol) generated by the compression algorithm.

    Returns:
        bitarray: The reconstructed binary data derived from the tuples.
    """
    result = bitarray()
    for offset, length, next_symbol in lz_list:
        for i in range(length):
            result.append(result[-offset + i])
        result.append(next_symbol)
    return result
