from typing import List, Tuple
from bitarray import bitarray


def basic_lempel_ziv(data: bitarray, search_length: int, match_length: int) -> List[Tuple[int, int, int]]:
    """
    Performs basic Lempel-Ziv compression on a binary array.

    Args:
        data (bitarray): The input binary data to be compressed.
        search_length (int): The maximum length of the search buffer.
        match_length (int): The maximum length of a matching substring.

    Returns:
        List[Tuple[int, int, int]]: A list of tuples representing the compressed data.
        Each tuple typically contains (offset, length, next_symbol).
    """
    result = []
    i = 0

    while i < len(data):
        best_offset = 0
        best_length = 0

        # Search for the longest match in the previous data
        for j in range(max(0, i - search_length), i):
            length = 0
            while (length < match_length and i + length < len(data) - 1 and data[j + length] == data[i + length]):
                length += 1

            if length > best_length:
                best_length = length
                best_offset = i - j

        # Next symbol after the match
        next_symbol = data[i + best_length] if (i + best_length) < len(data) else 0

        # Append the tuple (offset, length, next_symbol)
        result.append((best_offset, best_length, next_symbol))

        # Move the index forward
        i += best_length + 1

    return result


def convert_lampel_ziv_list_to_binarray(lz_list: List[Tuple[int, int, int]]) -> bitarray:
    """
    Converts a list of Lempel-Ziv tuples back into a binary array format.

    Args:
        lz_list (List[Tuple[int, int, int]]): The list of LZ tuples
        (offset, length, next_symbol) generated by the compression algorithm.

    Returns:
        bitarray: The reconstructed binary data derived from the tuples.
    """
    result = bitarray()
    for offset, length, next_symbol in lz_list:
        for i in range(length):
            result.append(result[-offset + i])
        result.append(next_symbol)
    return result
